version: "1"
services:
  neo4j:
    container_name: neo4jdemo
    image: "neo4j:4.4.0-enterprise"
    volumes:
      - "./data:/var/lib/neo4j/import"
      - "./plugins:/plugins"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_AUTH: "neo4j/test"
      NEO4J_server.http.listen_address: "localhost:7474"
      NEO4J_server.bolt.listen_address: "localhost:7687"
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
